on:
  release:
    types: [published]
  workflow_dispatch:

# This regex matches either a semver (e.g. 1.2.3)
# or a release candidate in one of these forms:
# 1.2.3-rc or 1.2.3-rc1
# Adjust the regex below as needed.
# The pattern:
#   ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ 
# matches to
#    [0-9]+.[0-9]+.[0-9]+
# or [0-9]+.[0-9]+.[0-9]+-rc optionally followed by digits

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Validating tag: $TAG"
          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
            echo "Tag matches semver."
          else
            echo "Error: tag does not match semvar"
            exit 1
          fi

  publish:
    needs: validate-tag
    name: Build and Upload module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Publish
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: viamrobotics/build-action@v1.6
        with:
          version: ${{ github.event.release.tag_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}

  publish-windows:
    needs: validate-tag
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          # As of August 2025, Tensorflow doesn't support Python 3.13.
          # https://github.com/tensorflow/tensorflow/issues/78774
          python-version: 3.10
      - name: Download CLI
        run: |
          curl -o viam.exe "https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-latest-windows-amd64.exe"
          ./viam.exe version
      - name: Set up repo
        run: make setup
      - name: Build module
        run: make dist/archive.tar.gz
      - name: Publish to the registry
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          ./viam.exe login api-key --key-id ${{ secrets.viam_key_id }} --key ${{ secrets.viam_key_value }}
          ./viam.exe module upload --platform windows/amd64 --version ${{ github.ref_name }} --upload dist/archive.tar.gz
